# Bài tập thực hành Buổi 2
## Perceptron – Hamming – Hopfield

**Hướng dẫn:**
- Làm phép tính tay trước (viết trên giấy hoặc comment).
- Điền code vào các ô `# TODO` để kiểm tra kết quả.
- Mỗi bài có ô đáp án ẩn — chỉ mở sau khi tự làm xong.

**Thang điểm:** A (2đ) + B (3đ) + C (3đ) + D (2đ) = 10 điểm

In [1]:
import numpy as np

---
## Bài A — Perceptron: Quyết định mua trà sữa (2 điểm)

**Tình huống:** Bạn chỉ mua trà sữa khi **ít nhất một** trong hai điều kiện đúng:
- `x₁ = 1`: Trời nóng trên 35°C
- `x₂ = 1`: Có voucher giảm giá

Đây là luật **OR**.

### Yêu cầu:
1. Điền bảng chân trị cho OR.
2. Chọn `w₁`, `w₂`, `b` sao cho Perceptron thực hiện đúng luật OR.
3. Tính `net` cho đủ 4 trường hợp và kiểm tra đầu ra `y`.

In [6]:
# Bài A.1: Điền trọng số và bias cho OR
# Gợi ý: giữ w1 = w2 = 1, chỉ cần tìm b sao cho
#   - (0,0) → net < 0
#   - (0,1), (1,0), (1,1) → net ≥ 0

w1 = 0.8  # TODO: điền giá trị
w2 = 0.8  # TODO: điền giá trị
b  = -0.4  # TODO: điền giá trị

def step(net):
    return 1 if net >= 0 else 0

# Bài A.2: Tính net và y cho 4 trường hợp
print("x1  x2  | net    | y  | Mua trà sữa?")
print("-" * 48)

truth_table = [(0, 0), (0, 1), (1, 0), (1, 1)]

for x1_val, x2_val in truth_table:
    net = w1*x1_val + w2*x2_val + b # TODO: tính net = w1*x1 + w2*x2 + b
    y = step(net)    # TODO: áp dụng hàm bước
    result = "MUA" if y == 1 else "Không"
    print(f" {x1_val}   {x2_val}  | {net:+.1f}  |  {y}  | {result}")

x1  x2  | net    | y  | Mua trà sữa?
------------------------------------------------
 0   0  | -0.4  |  0  | Không
 0   1  | +0.4  |  1  | MUA
 1   0  | +0.4  |  1  | MUA
 1   1  | +1.2  |  1  | MUA


In [7]:
# Bài A.3: Kiểm tra tự động — chạy sau khi điền xong
expected_or = [0, 1, 1, 1]
actual = []
for x1_val, x2_val in truth_table:
    net = w1 * x1_val + w2 * x2_val + b
    actual.append(step(net))

if actual == expected_or:
    print("✓ Đúng! Perceptron của bạn thực hiện OR chính xác.")
else:
    print(f"✗ Sai. Kết quả: {actual}, đáp án đúng: {expected_or}")
    print("  Gợi ý: bias cần đủ nhỏ để chỉ (0,0) cho net âm.")

✓ Đúng! Perceptron của bạn thực hiện OR chính xác.


<details>
<summary><b>👉 Xem đáp án Bài A</b></summary>

```python
w1, w2, b = 1.0, 1.0, -0.5
```

Kiểm tra:
- (0,0): net = 0+0−0.5 = −0.5 → y=0 ✓
- (0,1): net = 0+1−0.5 = +0.5 → y=1 ✓
- (1,0): net = 1+0−0.5 = +0.5 → y=1 ✓
- (1,1): net = 1+1−0.5 = +1.5 → y=1 ✓

</details>

---
## Bài B — Hamming: Nhận dạng chữ L, O, X (3 điểm)

**Bài toán:** Ba mẫu chuẩn trên lưới 3×3 (bipolar ±1):

```
L:  ■ □ □     O:  ■ ■ ■     X:  ■ □ ■
    ■ □ □         ■ □ ■         □ ■ □
    ■ ■ ■         ■ ■ ■         ■ □ ■
```

### Yêu cầu:
1. Mã hóa 3 mẫu thành vector bipolar 9 phần tử.
2. Cho input là chữ L bị thiếu nét dưới cùng bên phải:
   ```
   ■ □ □
   ■ □ □
   ■ ■ □  ← ô 9 bị sai
   ```
3. Tính điểm (tích vô hướng) với cả 3 mẫu và xác định mẫu thắng.

In [8]:
# Bài B.1: Mã hóa 3 mẫu chuẩn
# Quy ước: ■ = +1, □ = -1
# Quét hàng trái → phải, trên → dưới

pL = np.array([1, -1, -1,  1, -1, -1,  1,  1,  1])  # TODO: 9 giá trị cho chữ L
pO = np.array([1,  1,  1,  1, -1,  1,  1,  1,  1])  # TODO: 9 giá trị cho chữ O
pX = np.array([1, -1,  1, -1,  1, -1,  1, -1,  1])  # TODO: 9 giá trị cho chữ X

In [9]:
# Bài B.2: Mã hóa input (chữ L thiếu ô 9)

x = np.array([1, -1, -1,  1, -1, -1,  1,  1,  -1])  # TODO: 9 giá trị cho input

In [11]:
# Bài B.3: Tính điểm Hamming

score_L = pL @ x  # TODO: pL @ x
score_O = pO @ x  # TODO: pO @ x
score_X = pX @ x  # TODO: pX @ x

print(f"Điểm L: {score_L}")
print(f"Điểm O: {score_O}")
print(f"Điểm X: {score_X}")

names = ["L", "O", "X"]
# TODO: Xác định mẫu thắng
winner = names[np.argmax([score_L, score_O, score_X])]  # "L", "O" hay "X"?
print(f"\n→ Mẫu thắng: {winner}")

Điểm L: 7
Điểm O: 1
Điểm X: -1

→ Mẫu thắng: L


In [12]:
# Bài B.4: Trình bày phép nhân từng vị trí (để nộp phiếu tính tay)

print("Nhân từng vị trí pL với x:")
print(f"{'Vị trí':>8}", end='')
for i in range(1, 10):
    print(f"{i:>4}", end='')
print(f"{'Tổng':>6}")
print("-" * 52)

products = pL * x
print(f"pL·x  ", end='  ')
for p in products:
    print(f"{int(p):>4}", end='')
print(f"{int(products.sum()):>6}")

Nhân từng vị trí pL với x:
  Vị trí   1   2   3   4   5   6   7   8   9  Tổng
----------------------------------------------------
pL·x       1   1   1   1   1   1   1   1  -1     7


<details>
<summary><b>👉 Xem đáp án Bài B</b></summary>

```python
pL = np.array([ 1, -1, -1,  1, -1, -1,  1,  1,  1])
pO = np.array([ 1,  1,  1,  1, -1,  1,  1,  1,  1])
pX = np.array([ 1, -1,  1, -1,  1, -1,  1, -1,  1])

x  = np.array([ 1, -1, -1,  1, -1, -1,  1,  1, -1])  # L thiếu ô 9

score_L = pL @ x  # = 7  (8 ô trùng, 1 ô lệch)
score_O = pO @ x  # = 1  (5 ô trùng, 4 ô lệch)
score_X = pX @ x  # = -3 (3 ô trùng, 6 ô lệch)

winner = "L"
```

Giải thích: Input gần chữ L nhất (chỉ lệch 1 ô), điểm 7 cao nhất.

</details>

---
## Bài C — Hopfield: Nhớ hai trạng thái đèn phòng học (3 điểm)

**Tình huống:** Phòng học có 3 công tắc đèn: x₁ (bảng), x₂ (giữa), x₃ (cuối).

Hai chế độ đã lưu:
- **Mẫu 1 — Giảng bài:** Bật bảng, bật giữa, tắt cuối → `p¹ = (1, 1, −1)`
- **Mẫu 2 — Chiếu phim:** Tắt bảng, tắt giữa, bật cuối → `p² = (−1, −1, 1)`

### Yêu cầu:
1. Tính ma trận W 3×3 bằng luật Hebb.
2. Từ input lỗi `(1, −1, 1)` (ai đó bật bảng và cuối cùng lúc), chạy cập nhật bất đồng bộ.
3. Xác định mạng hội tụ về mẫu nào.

In [13]:
# Bài C.1: Khai báo hai mẫu
p1 = np.array([ 1,  1, -1])  # Giảng bài
p2 = np.array([-1, -1,  1])  # Chiếu phim

# Bài C.2: Tính ma trận W bằng luật Hebb
# Công thức: wij = (1/P)(pi1*pj1 + pi2*pj2), wii = 0
# P = 2 (số mẫu)

# TODO: Tính từng liên kết
w12 = 1  # ½(1×1 + (-1)×(-1)) = 1
w13 = -1 # ½(1×(-1) + (-1)×1) = -1
w23 = -1 # ½(1×(-1) + (-1)×1) = -1

print(f"w₁₂ = {w12}")
print(f"w₁₃ = {w13}")
print(f"w₂₃ = {w23}")

# TODO: Xây ma trận W đầy đủ
W = np.array([
    [0,    w12, w13],
    [w12,  0,   w23],
    [w13,  w23, 0  ],
])

print(f"\nMa trận W:\n{W}")

w₁₂ = 1
w₁₃ = -1
w₂₃ = -1

Ma trận W:
[[ 0  1 -1]
 [ 1  0 -1]
 [-1 -1  0]]


In [14]:
# Bài C.3: Cập nhật bất đồng bộ từ input lỗi

x = np.array([1, -1, 1])  # Input lỗi
print(f"Trạng thái ban đầu: x = {x.tolist()}\n")

# TODO: Cập nhật x₁
net1 = W[0] @ x  # = 0×1 + 1×(-1) + (-1)×1 = -2
x[0] = np.sign(net1) if net1 != 0 else x[0]
print(f"Cập nhật x₁: net₁ = {net1}, x₁ ← {x[0]}")

# TODO: Cập nhật x₂
net2 = W[1] @ x  # = 1×(-1) + 0×(-1) + (-1)×1 = -2
x[1] = np.sign(net2) if net2 != 0 else x[1]
print(f"Cập nhật x₂: net₂ = {net2}, x₂ ← {x[1]}")

# TODO: Cập nhật x₃
net3 = W[2] @ x  # = (-1)×(-1) + (-1)×(-1) + 0×1 = 2
x[2] = np.sign(net3) if net3 != 0 else x[2]
print(f"Cập nhật x₃: net₃ = {net3}, x₃ ← {x[2]}")

print(f"\nTrạng thái cuối: x = {x.tolist()}")

# TODO: So sánh với p1 và p2
if np.array_equal(x, p1):
    print("Mạng hội tụ về mẫu: p1 (Giảng bài)")
elif np.array_equal(x, p2):
    print("Mạng hội tụ về mẫu: p2 (Chiếu phim)")
else:
    print("Mạng không hội tụ về mẫu đã lưu")

Trạng thái ban đầu: x = [1, -1, 1]

Cập nhật x₁: net₁ = -2, x₁ ← -1
Cập nhật x₂: net₂ = -2, x₂ ← -1
Cập nhật x₃: net₃ = 2, x₃ ← 1

Trạng thái cuối: x = [-1, -1, 1]
Mạng hội tụ về mẫu: p2 (Chiếu phim)


<details>
<summary><b>👉 Xem đáp án Bài C</b></summary>

**C.2: Ma trận W**
```python
w12 = 0.5*(1*1 + (-1)*(-1)) = 0.5*(1+1) = 1
w13 = 0.5*(1*(-1) + (-1)*1) = 0.5*(-1-1) = -1
w23 = 0.5*(1*(-1) + (-1)*1) = 0.5*(-1-1) = -1

W = [[ 0,  1, -1],
     [ 1,  0, -1],
     [-1, -1,  0]]
```

**C.3: Cập nhật từ (1, -1, 1)**

Cập nhật x₁:
- net₁ = W[0]·x = 0×1 + 1×(−1) + (−1)×1 = −2
- x₁ ← sign(−2) = −1
- x = (−1, −1, 1)

Cập nhật x₂:
- net₂ = W[1]·x = 1×(−1) + 0×(−1) + (−1)×1 = −2
- x₂ ← sign(−2) = −1 (giữ)
- x = (−1, −1, 1)

Cập nhật x₃:
- net₃ = W[2]·x = (−1)×(−1) + (−1)×(−1) + 0×1 = 2
- x₃ ← sign(2) = +1 (giữ)
- x = (−1, −1, 1)

→ Hội tụ về **p² = (−1, −1, 1)** — chế độ Chiếu phim.

</details>

---
## Bài D — Tổng hợp: Chọn đúng mạng (2 điểm)

Với mỗi bài toán dưới đây, chọn mạng phù hợp nhất (Perceptron / Hamming / Hopfield) và giải thích ngắn gọn **vì sao**.

| # | Bài toán | Mạng | Vì sao? |
|---|----------|------|--------|
| 1 | App nhắc uống nước: chỉ nhắc khi nhiệt độ > 30°C **VÀ** đã qua 2 tiếng chưa uống | ... | ... |
| 2 | Máy quét xác định mã QR bị mờ thuộc sản phẩm A, B hay C | ... | ... |
| 3 | Hệ thống tự phục hồi lịch họp khi có vài slot bị xóa nhầm | ... | ... |
| 4 | Cổng bãi xe mở khi có thẻ **HOẶC** nhấn nút khẩn cấp | ... | ... |

In [15]:
# Bài D: Điền câu trả lời vào đây

answers = {
    1: {
        "mang": "Perceptron",
        "vi_sao": "Phân loại nhị phân",
    },
    2: {
        "mang": "Hamming",
        "vi_sao": "Nhận dạng mẫu gần nhất khi mã QR bị mờ.",
    },
    3: {
        "mang": "Hopfield",
        "vi_sao": "Phù hợp để khôi phục một mẫu đã lưu từ trạng thái bị lỗi hoặc thiếu một phần.",
    },
    4: {
        "mang": "Perceptron",
        "vi_sao": "Phù hợp để học hàm logic OR, cho đầu ra 1 khi thẻ hoặc nút khẩn cấp được kích hoạt.",
    },
}

for q, a in answers.items():
    print(f"Câu {q}: {a['mang']} — {a['vi_sao']}")

Câu 1: Perceptron — Phân loại nhị phân
Câu 2: Hamming — Nhận dạng mẫu gần nhất khi mã QR bị mờ.
Câu 3: Hopfield — Phù hợp để khôi phục một mẫu đã lưu từ trạng thái bị lỗi hoặc thiếu một phần.
Câu 4: Perceptron — Phù hợp để học hàm logic OR, cho đầu ra 1 khi thẻ hoặc nút khẩn cấp được kích hoạt.


<details>
<summary><b>👉 Xem đáp án Bài D</b></summary>

| # | Mạng | Vì sao? |
|---|------|--------|
| 1 | **Perceptron** | Hai điều kiện AND → quyết định Có/Không, tách tuyến tính. |
| 2 | **Hamming** | Có sẵn mẫu chuẩn (A,B,C), cần so khớp input bị nhiễu với mẫu gần nhất. |
| 3 | **Hopfield** | Cần phục hồi thông tin bị mất từ mẫu đã lưu — nhớ liên tưởng. |
| 4 | **Perceptron** | Hai điều kiện OR → quyết định mở/đóng, tách tuyến tính. |

</details>

---
## Checklist nộp bài

- [ ] Bài A: Perceptron OR chạy đúng 4 trường hợp
- [ ] Bài B: Tính đúng 3 điểm Hamming và chọn được mẫu thắng
- [ ] Bài C: Ma trận W đúng + cập nhật hội tụ về đúng mẫu
- [ ] Bài D: Chọn đúng mạng cho 4 bài toán + có giải thích

**Nộp:** File notebook này (đã chạy) + ảnh phiếu tính tay (nếu có).